### ISSUE TITLE
Modify YoloV3 for Smaller Objects

### ISSUE THREAD

**Issue by d-j-kendall** [dkendall100/beating_roulette#11]
To implement object detection for smaller objects, we need to change hyperparameters and the configuratin of the network.

After doing some research and reaching out I have found these sources.

[Low Feature Map Resolution](https://medium.com/@jonathan_hui/ssd-or-yolo-all-have-problems-to-detect-small-objects-comparing-with-regional-based-object-aff02ba69d28)

Talked to devlopers on darknet github and got response
 _Re: [pjreddie/darknet] How do I set the grid size when I use yolo v3? (#1042)_

On changing grid size for more resolution.

This was the suggested 
[configuration file](https://github.com/dkendall100/beating_roulette/files/3195545/yolov3_train.cfg.txt) to enable a smaller grid size.

**Comment by dkendall100** [comment]
This can be closed, @alpizano @mmassom96. We were able to successfully use Yolov3_Tiny_3L to identify small objects. This config only has 3 yolo layers, and many less convolutional layers.

**Comment by d-j-kendall** [comment]
This can be closed, @alpizano @mmassom96. We were able to successfully use Yolov3_Tiny_3L to identify small objects. This config only has 3 yolo layers, and many less convolutional layers.
