### ISSUE TITLE
Use PyTorch to Solve Classification Problem

### ISSUE THREAD

**Issue by d-j-kendall** [dkendall100/beating_roulette#3]
One of us should be able to use PyTorch to solve a classification problem. Code network using python and pytorch and push it into a separate folder in the learning exercise's folder in our repository

**Comment by dkendall100** [comment]
Here is a good tutorial.
https://pytorch.org/tutorials/beginner/blitz/cifar10_tutorial.html

I think it would be a good start

**Comment by d-j-kendall** [comment]
Al, Here is the 60-minute blitz you and Matt can work on together.
Al you might want to use your personal computer for training since you have a decent Nvidia card.

https://pytorch.org/tutorials/beginner/deep_learning_60min_blitz.html

Once you train the classifier, put it in the folder(create the folder)

examples/training_a_classifer

then push it up to the master branch

**Comment by alpizano** [comment]
Thank you

**Comment by d-j-kendall** [comment]
Al and I both implemented classification neural networks and seem to have a good enough understanding.
Closing this issue
